// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lee_Final.Models
{
    public partial class Assignment
    {
        public Assignment()
        {
            ClassAssignments = new HashSet<ClassAssignment>();
        }

        public string AssignmentId { get; set; }
        public string AssignmentCode { get; set; }
        public string AssignmentName { get; set; }
        public string AssignmentDescription { get; set; }
        public DateTime? AssignmentDueDate { get; set; }

        public virtual ICollection<ClassAssignment> ClassAssignments { get; set; }
    }
}