// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lee_Final.Models
{
    public partial class FacultyClass
    {
        public string FacultyClassesId { get; set; }
        public string ClassId { get; set; }
        public string FacultyId { get; set; }

        public virtual Class Class { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}